include $(APPDIR)/Make.defs

PROGNAME = lvgldemo
PRIORITY = $(CONFIG_EXAMPLES_LVGLDEMO_PRIORITY)
STACKSIZE = $(CONFIG_EXAMPLES_LVGLDEMO_STACKSIZE)
MODULE = $(CONFIG_EXAMPLES_LVGLDEMO)

MAINSRC = lvgldemo.c

CSRCS += jp_font_16_hiragana.c
CSRCS += jp_font_24.c
CSRCS += dict.c


include $(APPDIR)/Application.mk
